apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: https://sibaacr.azurecr.io/hello-world:1
        imagePullPolicy: IfNotPresent
        imagePullSecrets:
        - name: sops-gpg
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        command:
        - ./dotnet
        - HelloWorld.dll
        livenessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:80
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:80
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi