apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: Opaque
data:
  docker-server: sibaacr.azurecr.io
  docker-username: 28b25687-cd5e-4bd7-a857-d72a37d1fb30
  docker-password: rgL2z8Wq9Um~9r94RoDXIXm7s~nzrJg9Y2