apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  type: ClusterIP
  selector:
    app: helloworld
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http